name: Simple Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analyse:
    name: Lint with flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 .
  
  package:
    name: Zip the application
    runs-on: ubuntu-latest
    needs: analyse  # Run only after analyse succeeds

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create zip archive
        run: |
          zip -r app_package.zip .
      
      - name: Upload zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged-app
          path: app_package.zip
